// Interval definitions
#define MILLIS 1
#define SECONDS 1000
#define MINUTES 60 * SECONDS
#define HOURS 60 * MINUTES
#define DAYS 24 * HOURS
#define MILLIS_TO_MICROS 1000
#define SECONDS_TO_MICROS SECONDS * MILLIS_TO_MICROS
